### PR TITLE
chore: fix sonar alerts

### LINKED ISSUE #210: Review SonarCloud alerts

### PR DESCRIPTION
**Pull request by basmasking**
Fixes #210 

Changes proposed in this pull request:
- fixed code smells
- updated hooks to be consistent with react best practices
- fixed some bugs
- added hooks linter

@MaskingTechnology/comify

### CODE REVIEW

File: src/domain/post/toggleRating.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export default async function toggleRating(requester: Requester, postId: string)
 
     try
     {
-        rating = await updateRating(requester, postId, undefined);
```
Comment (petermasking) [inline src/domain/post/toggleRating.ts:13]: I think we should restore this, and make the parameter not optional anymore to make it more explicit.

File: src/integrations/authentication/definitions/types.ts [hunk 2]
```diff
@@ -7,13 +7,11 @@ export type Identity = {
     email_verified: boolean;
 };
 
-export type Token = string;
```
Comment (petermasking) [inline src/integrations/authentication/definitions/types.ts:10]: For the database implementation we've chosen to keep using this 'useless' types to make it more clear (and changeable in to future).

File: src/webui/components/common/ErrorBoundary.tsx [hunk 3]
```diff
@@ -5,7 +5,7 @@ type ViewProps = {
     error: unknown;
 };
 
-export type Props = {
+type Props = {
     element: React.ComponentType<ViewProps>;
     children: React.ReactNode;
```
Comment (petermasking) [inline src/webui/components/common/ErrorBoundary.tsx:10]: Missing readonly?

File: src/webui/designsystem/components/dropdown/Dropdown.css [hunk 4]
```diff
@@ -5,10 +5,9 @@
     --background-color-options-hover: var(--color-background-hover);
     --arrow-color: var(--color-alert-foreground);
     --border-color: var(--color-border);
-}
 
-.ds-selection
-{
+
+
```
Comment (petermasking) [inline src/webui/designsystem/components/dropdown/Dropdown.css:10]: Three empty lines is maybe a bit much. We've discussed keeping it at one line.

File: test/domain/relation/explore.spec.ts [hunk 5]
```diff
@@ -31,7 +31,7 @@ describe('domain/relation/explore', () =>
         expect(relations[0]).toBeUndefined();
     });
 
-    it('should find relations based on search fullname', async () =>
+    it('should find relations based on searchfull name', async () =>
```
Comment (petermasking) [inline test/domain/relation/explore.spec.ts:34]: This is even worse 😉

**Review by petermasking — CHANGES_REQUESTED** [review]

**Review by petermasking — APPROVED** [review]
